services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    depends_on:
      - backend
    ports:
      - "8080:8080"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://dataroom:dataroom@postgres:5432/dataroom?schema=public
      UPLOAD_DIR: /app/uploads
    expose:
      - "8080"
    volumes:
      - upload-data:/app/uploads

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: dataroom
      POSTGRES_USER: dataroom
      POSTGRES_PASSWORD: dataroom
    ports:
      - "5438:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  upload-data:
